language: java
install: true
jdk: oraclejdk11
script:
- ./gradlew build sonarqube pushImageToDockerHub
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
- rm -fr $HOME/.gradle/caches/*/scripts/
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
notifications:
  slack:
    secure: hPRqBGTsxtrthL8xupB7niwmVL65mW9yaQhdNhBkx/foahAZSadxS4QExS9QfwJOKS2bICLzNvNBsGDK/z7UBbIax6GO693iZtNCrAMcXq+x2okhP1fI8JAdzjDlZBKhkzUVyfHPAOnbK/2h9/lBR9HnrB2ZEYA/LPb6lC5JZ92IPJ9HVgiPHyNwft1CkT/q2IZJCC2zAlKYFDNWn7NRaJf+C6G6pQtxsPsZJvrH7gTkk4J0djvLsaDvxYCFPSgV8bDDOYXd1nCPfbV3yqC4H1Mqrw/Qzeh5jktk5xopH1NsuY363jVEgbFZ09dzSJYgoeUUJNuQoC3EaZ1NY6APqoXHUASv6fKKr9M9F2PZsh/yLv+qDc3b/1w3pYwwo8ImXXblRkFofwF1bM5tm5HqryxO5Cem4rsQ4lECdGggxYB+OsddL2Rw920bAzdgwF5CZWt1A0m7VWEZWpBSyq4/k5T/9lMJLDlDYB/t0L4s7uM4VP208FG6TxY1QUcqin9+BaKwC4ou9Nt/bBIC5i03LcyIP94uPR7Z8DTRIm4/2D3lpxZ0mUJAdcZcXXOPBMuAnWxpI1wSW+AI8dzvv8Xh51su3S+NR2JJfC55MiQmHskfstXP7+YyL1tXVS3lwu6clJpN58/o4deThNDHatoMns/5k0dLNY58P04XlIfqojc=
